// src/lib/db.ts
// Main database utility functions
import { Pool } from '@neondatabase/serverless';
import { 
  getAllProperties,
  getPropertyById,
  createProperty,
  updateProperty,
  deleteProperty,
  getFeaturedProperties,
  getPropertyTypes,
  getPropertyLocations,
  getAllUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  getPageContent,
  getAllPages,
  createPage,
  updatePage,
  deletePage,
  getUserFavorites,
  addPropertyToFavorite,
  removePropertyFromFavorite,
  getPropertyDetailContent,
  getHomeHeroContent,
  getAboutPageContent,
  getServicesPageContent,
  getBlogPost,
  getAllBlogPosts,
  createBlogPost,
  updateBlogPost,
  deleteBlogPost,
  getAllReviews,
  getReviewById,
  createReview,
  updateReview,
  deleteReview,
  getInquiryById,
  createInquiry,
  updateInquiryStatus,
  getAllInquiries,
  deleteInquiry,
  getAppointmentById,
  createAppointment,
  updateAppointment,
  deleteAppointment,
  getAllAppointments,
  updateUserPassword,
  hashPassword,
  initializeTables,
  checkAdminUser,
  createAdminUser,
  getAllPropertyImages,
  uploadPropertyImage,
  deletePropertyImage,
  getPropertiesWithFilters,
  getDashboardStats,
  getUserByEmail,
  removePropertyFromFavorite as removePropertyFromFavorites,
} from './db-actions';

const DATABASE_URL = process.env.DATABASE_URL;

// Helper function to get database pool
export const getDbPool = () => {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL is not configured');
  }

  return new Pool({
    connectionString: DATABASE_URL,
  });
};

// Re-export all database action functions
export {
  getAllProperties,
  getPropertyById,
  createProperty,
  updateProperty,
  deleteProperty,
  getFeaturedProperties,
  getPropertyTypes,
  getPropertyLocations,
  getAllUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  getPageContent,
  getAllPages,
  createPage,
  updatePage,
  deletePage,
  getUserFavorites,
  addPropertyToFavorite,
  removePropertyFromFavorite,
  getPropertyDetailContent,
  getHomeHeroContent,
  getAboutPageContent,
  getServicesPageContent,
  getBlogPost,
  getAllBlogPosts,
  createBlogPost,
  updateBlogPost,
  deleteBlogPost,
  getAllReviews,
  getReviewById,
  createReview,
  updateReview,
  deleteReview,
  getInquiryById,
  createInquiry,
  updateInquiryStatus,
  getAllInquiries,
  deleteInquiry,
  getAppointmentById,
  createAppointment,
  updateAppointment,
  deleteAppointment,
  getAllAppointments,
  updateUserPassword,
  hashPassword,
  initializeTables,
  checkAdminUser,
  createAdminUser,
  getAllPropertyImages,
  uploadPropertyImage,
  deletePropertyImage,
  getPropertiesWithFilters,
  getDashboardStats,
  getUserByEmail,
  removePropertyFromFavorites,
};